eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8899
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-manager:
      path: /mall-manager/**
      service-id: mall-manager-ms
    api-content:
      path: /mall-content/**
      service-id: mall-content-ms